name: Npm publish

on:
    release:
        types: [created]
        # push:
        #     branches: [master]

jobs:
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3
    #           with:
    #               fetch-depth: 0

    #         - name: Install pnpm
    #           uses: pnpm/action-setup@v2

    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #               registry-url: https://registry.npmmirror.com
    #               cache: pnpm

    #         - run: pnpm install

    #         # - run: npx changelogithub --no-group
    #         #   continue-on-error: true
    #         #   env:
    #         #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #         - run: pnpm run dist
    #           env:
    #               NODE_OPTIONS: --max-old-space-size=6144

    publish-gpr:
        # needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7.7.0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmmirror.com
                  cache: pnpm

            - run: pnpm install

            # - run: npx changelogithub --no-group
            #   continue-on-error: true
            #   env:
            #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - run: pnpm run dist
              env:
                  NODE_OPTIONS: --max-old-space-size=6144

            - name: Gen .npmrc
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

            - run: pnpm pub
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            - run: curl -X PUT -d "sync_upstream=true" "https://registry-direct.npmmirror.com/clipboard-parser/sync"
